---
#- name: Set permissions for Radarr config directory
  #ansible.builtin.include_tasks: "../../../shared-tasks/permissions.yml"
  #vars:
    #target_dir: "{{ app_data_dir }}/radarr-4k"

- name: Start 4k-films container
  community.docker.docker_container:
    image_name_mismatch: "recreate"
    pull: "always"
    name: 4k-films
    image: linuxserver/radarr:5.14.0
    env:
    networks:
      - name: web
    published_ports: ["5656:5656"]
    labels:
      traefik.enable: "true"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/traefik/traefik/master/docs/content/assets/img/traefik.logo-dark.png?raw=true"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "https://proxy.{{ DOMAIN }}/dashboard/"

      # Dashboard configuration
      traefik.http.routers.traefik-dashboard.rule: "Host(`proxy.{{ DOMAIN }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      traefik.http.routers.traefik-dashboard.entrypoints: "https"
      traefik.http.routers.traefik-dashboard.service: "api@internal"
      traefik.http.routers.traefik-dashboard.tls.certresolver: "letsencrypt"
      traefik.http.middlewares.traefik-auth.basicauth.users: "{{ username }}:{{ PASSWORD_HASH }}"
      traefik.http.middlewares.traefik-dashboard-redirect.headers.customresponseheaders.X-Robots-Tag: "noindex,nofollow"
      traefik.http.routers.traefik-dashboard.middlewares: "traefik-auth, traefik-dashboard-redirect"

    log_driver: json-file
    log_options:
      max-file: "1"
      max-size: 10m
    restart_policy: always
    volumes:
      - "{{ app_data_dir }}/radarr-4k:/config"
      - "{{ dwnlds_dir }}:/downloads:rw"
      - "{{ media_dir }}/4k-movies:/movies:rw"
      - "{{ media_dir }}/old-4k:/old-4k"
    security_opts:
      - no-new-privileges:true
      - apparmor=docker-default
    read_only: true
    tmpfs:
      - "/run:exec"
    memory: "1g"
    cpus: 1



- name: Start 4k-tv container
  community.docker.docker_container:
    image_name_mismatch: "recreate"
    pull: "always"
    name: 4k-tv
    image: linuxserver/sonarr:4.0.10
    published_ports: ["6767:6767"]
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
    ipc_mode: private
    labels:
      net.unraid.docker.icon: "https://github.com/themepark-dev/theme.park/blob/master/css/addons/sonarr/sonarr-4k-logo/sonarr-4k.png?raw=true"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "https://4k-tv.johnflix.uk"
      traefik.enable: "true"
      traefik.http.routers.4k-tv.tls.certresolver: "letsencrypt"
      traefik.http.services.4k-tv.loadbalancer.server.port: "6767"
      traefik.http.routers.4k-tv-router.rule: "Host(`4k-tv.{{ DOMAIN }}`)"
      traefik.http.routers.4k-tv-router.entrypoints: "https"
      #traefik.http.routers.4k-tv-router.middlewares: "internal-ipallowlist@file"
    log_driver: json-file
    log_options:
      max-file: "1"
      max-size: 10m
    networks:
      - name: web
    restart_policy: always
    volumes:
      - "{{ app_data_dir }}/sonarr-4k:/config"
      - "{{ dwnlds_dir }}:/downloads:rw"
      - "{{ media_dir }}/4k-tv-shows:/tv-shows:rw"
      - "{{ media_dir }}/old-4k:/old-4k"
    working_dir: /
    security_opts:
      - no-new-privileges:true
      - apparmor=docker-default
    #read_only: true
    #tmpfs:
      #- "/run:exec"
    memory: "1g"
    cpus: 1


#- name: Set permissions for 4k-tv directory
  #ansible.builtin.include_tasks: "../../../shared-tasks/permissions.yml"
  #vars:
    #target_dir: "{{ media_dir }}/4k-tv-shows"
