---
- name: Create database for {{ app.name }}
  community.postgresql.postgresql_db:
    login_host: localhost
    login_user: "{{ postgres_admin_user }}"
    login_password: "{{ PASSWORD }}"
    name: "{{ app.db_name }}"
    state: present

- name: Create user for {{ app.name }} and grant privileges
  community.postgresql.postgresql_user:
    login_host: localhost
    login_user: "{{ postgres_admin_user }}"
    login_password: "{{ PASSWORD }}"
    name: "{{ app.db_user }}"
    password: "{{ app.db_password }}"
    priv: "{{ app.db_name }}:ALL"  # Proper format for database-level privileges
    state: present