---
#- name: Set permissions for audiobook config directory
  #ansible.builtin.include_tasks: "../../../shared-tasks/permissions.yml"
  #vars:
    #target_dir: "{{ app_data_dir }}/readarr-audio/"

- name: Start audiobook container
  ansible.builtin.include_tasks: ../../../shared-tasks/docker-app.yml
  vars:
    app_name: audiobook
    app_image: "lscr.io/linuxserver/readarr:0.3.17-develop"
    app_networks:
      - name: web
    app_published_ports: ["8686:8686"]
    app_env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ timezone }}"
    app_volumes:
      - "{{ app_data_dir }}/readarr-audio/:/config"
      - "{{ media_dir }}/audiobooks/:/audiobooks"
      - "{{ dwnlds_dir }}:/downloads"
    app_icon_url: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/readarr-logo.png"
    app_webui_url: "http://[IP]:[PORT:8686]"
    app_log_driver: json-file
    app_log_options:
      max-file: "1"
      max-size: 10m
    app_restart_policy: unless-stopped
    app_security_opts:
      - no-new-privileges:true
      - apparmor=docker-default
    app_memory: "1g"
    app_cpus: 1
    app_traefik_enable: true
    app_port: 8686

#- name: Set permissions for audibooks
  #ansible.builtin.include_tasks: "../../../shared-tasks/permissions.yml"
  #vars:
    #target_dir: "{{ media_dir }}/audiobooks/"
#
#- name: Set permissions for audible config directory
  #ansible.builtin.include_tasks: "../../../shared-tasks/permissions.yml"
  #vars:
    #target_dir: "{{ app_data_dir }}/audiobookshelf/"

- name: Start audible container
  ansible.builtin.include_tasks: ../../../shared-tasks/docker-app.yml
  vars:
    app_name: audible
    app_image: "ghcr.io/advplyr/audiobookshelf:latest"
    app_networks:
      - name: web
    app_published_ports: ["1337:1337"]
    app_env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ timezone }}"
      PORT: "1337"
    app_volumes:
      - "{{ media_dir }}/audiobooks/:/audiobooks"
      - "{{ app_data_dir }}/audiobookshelf/metadata:/metadata"
      - "{{ app_data_dir }}/audiobookshelf/:/config"
    app_icon_url: "https://www.audiobookshelf.org/Logo.png"
    app_webui_url: "http://[IP]:[PORT:1337]"
    app_log_driver: json-file
    app_log_options:
      max-file: "1"
      max-size: 10m
    app_restart_policy: unless-stopped
    app_security_opts:
      - no-new-privileges:true
      - apparmor=docker-default
    app_memory: "1g"
    app_cpus: 1
    app_traefik_enable: true
    app_port: 1337
