- name: Set permissions for Downloads directory
  ansible.builtin.include_tasks: "../../../shared-tasks/permissions.yml"
  vars:
    target_dir: "{{ dwnlds_dir }}:/downloads"
    app_owner: downloads

- name: Start Gluetun container
  community.docker.docker_container:
    name: gluetun
    image: qmcgaw/gluetun:v3
    restart_policy: always
    networks:
      - name: web
    capabilities:
      - NET_ADMIN
    volumes:
      - "{{ app_data_dir }}/gluetun:/gluetun"
    env:
      VPN_SERVICE_PROVIDER: "private internet access"
      OPENVPN_USER: "{{ OPENVPN_USER }}"
      OPENVPN_PASSWORD: "{{ OPENVPN_PASSWORD }}"
      SERVER_REGIONS: "Netherlands"
      VPN_PORT_FORWARDING: "on"
      FIREWALL_OUTBOUND_SUBNETS:  "{{ subnet }}"
      BLOCK_MALICIOUS: "on"
      BLOCK_SURVEILLANCE: "on"
      BLOCK_ADS: "on"
    ports:
      - "8112:8112"
      - "9696:9696"
      - "58846:58846"
    labels:
      traefik.enable: "true"
      traefik.http.routers.gluetun-deluge-rtr.rule: "Host(`downloads.{{ DOMAIN }}`)"
      traefik.http.routers.gluetun-deluge-rtr.entrypoints: "https"
      ## HTTP Services
      traefik.http.routers.gluetun-deluge-rtr.service: "gluetun-deluge"
      traefik.http.routers.gluetun-deluge.tls.certresolver: "letsencrypt"
      traefik.http.services.gluetun-deluge.loadbalancer.server.portt: "8112"
      traefik.http.routers.gluetun-delugesecure.entrypoints: "https"
      traefik.http.routers.gluetun-delugesecure.rule: "Host(`downloads.{{ DOMAIN }}`)"
      traefik.http.routers.gluetun-delugesecure.tls: "true"
      traefik.http.routers.gluetun-delugesecure.tls.certresolver: "letsencrypt"
      traefik.http.routers.gluetun-delugesecure.service: "gluetun-deluge"
      # Traefik label for Prowlarr (on Gluetun's network)
      traefik.http.routers.gluetun-prowlarr.rule: "Host(`torrents.{{ DOMAIN }}`)"
      traefik.http.routers.gluetun-prowlarr.entrypoints: "https"
      traefik.http.routers.gluetun-prowlarr.tls.certresolver: "letsencrypt"
      traefik.http.services.gluetun-prowlarr.loadbalancer.server.port: "9696"
      # Unraid Labels
      net.unraid.docker.icon: "https://github.com/qdm12/gluetun/blob/master/doc/logo_256.png"
      net.unraid.docker.managed: "dockerman"

- name: Start Deluge container
  community.docker.docker_container:
    name: deluge
    image: linuxserver/deluge:2.1.1
    restart_policy: always
    network_mode: "container:gluetun"
    env:
      PUID: "2000"
      PGID: "{{ media_pgid }}"
      TZ: "Etc/UTC"
      DELUGE_LOGLEVEL: "warn"   # Optional
      UMASK: "002"
    volumes:
      - "{{ app_data_dir }}/deluge:/config"
      - "{{ dwnlds_dir }}:/downloads"
    labels:
      net.unraid.docker.icon: "https://upload.wikimedia.org/wikipedia/commons/c/c5/Deluge_icon.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "https://downloads.{{ DOMAIN }}"

- name: Start Gluetun Deluge Port Manager container
  community.docker.docker_container:
    name: gluetun-deluge-port-manager
    image: plaexmstr/gluetun-deluge-port-manager
    restart_policy: always
    volumes:
      - "{{ app_data_dir }}/gluetun:/gluetun"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    network_mode: "container:gluetun"
    env:
      DELUGE_PORT: "8112"
      PORT_FORWARDED: "/tmp/gluetun/piaportforward.json"

- name: Start Prowlarr container
  community.docker.docker_container:
    name: torrents
    image: lscr.io/linuxserver/prowlarr:1.25.4
    restart_policy: always
    network_mode: "container:gluetun"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ app_data_dir }}/prowlarr:/config"
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/prowlarr-banner.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "https://torrents.{{ DOMAIN }}"
