#- name: Set permissions for Downloads config
  #ansible.builtin.include_tasks: "../../../shared-tasks/permissions.yml"
  #vars:
    #target_dir: "{{ app_data_dir }}/deluge"
#
#- name: Set permissions for Downloads directory
  #ansible.builtin.include_tasks: "../../../shared-tasks/permissions.yml"
  #vars:
    #target_dir: "{{ dwnlds_dir }}"

- name: Start Gluetun container
  community.docker.docker_container:
    name: gluetun
    image: qmcgaw/gluetun:v3
    restart_policy: always
    networks:
      - name: web
    capabilities:
      - NET_ADMIN
    volumes:
      - "{{ app_data_dir }}/gluetun:/gluetun"
    env:
      VPN_SERVICE_PROVIDER: "private internet access"
      OPENVPN_USER: "{{ OPENVPN_USER }}"
      OPENVPN_PASSWORD: "{{ OPENVPN_PASSWORD }}"
      SERVER_REGIONS: "Netherlands"
      VPN_PORT_FORWARDING: "on"
      FIREWALL_OUTBOUND_SUBNETS:  "{{ subnet }}"
      BLOCK_MALICIOUS: "on"
      BLOCK_SURVEILLANCE: "on"
      BLOCK_ADS: "on"
    ports:
      - "8112:8112"
      - "9696:9696"
      - "58846:58846"
    labels:
      traefik.enable: "true"

      # Unraid Labels
      net.unraid.docker.icon: "https://raw.githubusercontent.com/binhex/docker-templates/refs/heads/master/binhex/images/deluge-icon.png?raw=true"
      net.unraid.docker.managed: "dockerman"

- name: Start Deluge container
  community.docker.docker_container:
    name: deluge
    image: linuxserver/deluge:2.1.1
    restart_policy: always
    network_mode: "container:gluetun"
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ:  "{{ timezone }}"
      DELUGE_LOGLEVEL: "warn"   # Optional
    volumes:
      - "{{ app_data_dir }}/deluge:/config"
      - "{{ dwnlds_dir }}:/downloads"
    security_opts:
      - no-new-privileges:true
      - apparmor=docker-default
    labels:
      net.unraid.docker.icon: "https://upload.wikimedia.org/wikipedia/commons/c/c5/Deluge_icon.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "https://downloads.{{ DOMAIN }}"

- name: Start Gluetun Deluge Port Manager container
  community.docker.docker_container:
    name: gluetun-deluge-port-manager
    image: plaexmstr/gluetun-deluge-port-manager
    restart_policy: always
    volumes:
      - "{{ app_data_dir }}/gluetun:/gluetun"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    network_mode: "container:gluetun"
    env:
      DELUGE_PORT: "8112"
      PORT_FORWARDED: "/tmp/gluetun/piaportforward.json"

- name: Start Prowlarr container
  community.docker.docker_container:
    name: torrents
    image: lscr.io/linuxserver/prowlarr:1.25.4
    restart_policy: always
    network_mode: "container:gluetun"
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ app_data_dir }}/prowlarr:/config"
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/prowlarr-banner.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "https://torrents.{{ DOMAIN }}"
