#- name: Set permissions for Downloads config
  #ansible.builtin.include_tasks: "../../../shared-tasks/permissions.yml"
  #vars:
    #target_dir: "{{ app_data_dir }}/deluge"
#
#- name: Set permissions for Downloads directory
  #ansible.builtin.include_tasks: "../../../shared-tasks/permissions.yml"
  #vars:
    #target_dir: "{{ dwnlds_dir }}"

- name: Start Gluetun container
  ansible.builtin.include_tasks: "../../../shared-tasks/docker-app.yml"
  vars:
    app_name: gluetun
    app_image: qmcgaw/gluetun:v3
    app_networks:
      - name: web
    app_capabilities:
      - NET_ADMIN
    app_volumes:
      - "{{ app_data_dir }}/gluetun:/gluetun"
    app_env:
      VPN_SERVICE_PROVIDER: "private internet access"
      OPENVPN_USER: "{{ OPENVPN_USER }}"
      OPENVPN_PASSWORD: "{{ OPENVPN_PASSWORD }}"
      SERVER_REGIONS: "Netherlands"
      VPN_PORT_FORWARDING: "on"
      FIREWALL_OUTBOUND_SUBNETS:  "{{ subnet }}"
      BLOCK_MALICIOUS: "on"
      BLOCK_SURVEILLANCE: "on"
      BLOCK_ADS: "on"
      UPDATER_PERIOD: "24h"
    app_published_ports:
      - "8112:8112"
      - "9696:9696"
      - "58846:58846"
    app_traefik_enable: "false"
    app_icon_url: "https://raw.githubusercontent.com/qdm12/gluetun/master/doc/logo_256.png"
    app_extra_labels:
      net.unraid.docker.managed: "dockerman"

- name: Start Deluge container
  ansible.builtin.include_tasks: "../../../shared-tasks/docker-app.yml"
  vars:
    app_name: deluge
    app_image: linuxserver/deluge:2.1.1
    app_network_mode: "container:gluetun"
    app_published_ports: []
    app_env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ:  "{{ timezone }}"
      DELUGE_LOGLEVEL: "warn"
    app_volumes:
      - "{{ app_data_dir }}/deluge:/config"
      - "{{ dwnlds_dir }}:/downloads"
    app_security_opts:
      - no-new-privileges:true
      - apparmor=docker-default
    app_icon_url: "https://deluge-torrent.org/images/deluge_logo.png"
    app_extra_labels:
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "https://downloads.{{ DOMAIN }}"
    app_traefik_enable: "false"

- name: Start Gluetun Deluge Port Manager container
  ansible.builtin.include_tasks: "../../../shared-tasks/docker-app.yml"
  vars:
    app_name: gluetun-deluge-port-manager
    app_volumes:
      - "{{ app_data_dir }}/gluetun:/gluetun"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    app_network_mode: "container:gluetun"
    app_published_ports: []
    app_env:
      DELUGE_PORT: "8112"
      PORT_FORWARDED: "/tmp/gluetun/piaportforward.json"
    app_traefik_enable: "false"

- name: Start Prowlarr container
  ansible.builtin.include_tasks: "../../../shared-tasks/docker-app.yml"
  vars:
    app_name: torrents
    app_image: lscr.io/linuxserver/prowlarr:1.25.4
    app_network_mode: "container:gluetun"
    app_published_ports: []
    app_env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ timezone }}"
    app_volumes:
      - "{{ app_data_dir }}/prowlarr:/config"
    app_icon_url: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/prowlarr-banner.png"
    app_extra_labels:
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "https://torrents.{{ DOMAIN }}"
    app_traefik_enable: "false"
