---
- name: Check if Docker is installed
  command: docker --version
  register: docker_check
  ignore_errors: yes

- name: Fail if Docker is not installed
  fail:
    msg: "Docker is not installed. Please install Docker before running this playbook."
  when: docker_check.rc != 0
