---
- name: Check if Docker is installed
  ansible.builtin.command: docker --version
  register: docker_check
  ignore_errors: true

- name: Fail if Docker is not installed
  ansible.builtin.fail:
    msg: "Docker is not installed. Please install Docker before running this playbook."
  when: docker_check.rc != 0 and docker_check.changed

- name: Check if directory /mnt/user/appdata/ exists
  ansible.builtin.stat:
    path: /mnt/user/appdata/
  register: appdata_dir_check

- name: Fail if directory /mnt/user/appdata/ does not exist
  ansible.builtin.fail:
    msg: "Directory /mnt/user/appdata/ does not exist. Please create it before continuing."
  when: not appdata_dir_check.stat.exists

- name: Install requests library
  ansible.builtin.pip:
    name: requests
    state: present

- name: Check if Docker network "web" exists
  community.docker.docker_network_info:
    name: web
  register: network_info

- name: Create Docker network "web" if it does not exist
  community.docker.docker_network:
    name: web
    state: present
  when: not network_info.exists
