#---
#- name: Ensure the 'media' group exists
  #ansible.builtin.group:
    #name: media
    #gid: 2000
    #state: present
    #system: true
#
#- name: Create system user for Sonarr
  #ansible.builtin.user:
    #name: tv
    #group: media
    #uid: 2001
    #shell: /usr/sbin/nologin
    #home: /var/lib/sonarr
    #create_home: no
    #system: yes
    #append: yes
#
#- name: Create system user for Radarr
  #ansible.builtin.user:
    #name: films
    #group: media
    #uid: 2002
    #shell: /usr/sbin/nologin
    #home: /var/lib/radarr
    #create_home: no
    #system: yes
    #append: yes
#
#- name: Create system user for Plex
  #ansible.builtin.user:
    #name: plex
    #group: media
    #uid: 2003
    #shell: /usr/sbin/nologin
    #home: /var/lib/plex
    #create_home: no
    #system: yes
    #append: yes
#
#- name: Create system user for downloads
  #ansible.builtin.user:
    #name: downloads
    #group: media
    #uid: 2000
    #shell: /usr/sbin/nologin
    #home: /var/lib/downloads
    #create_home: no
    #system: yes
    #append: yes


#Set permissions
#downloads
#- name: Set permissions for the downloads directory
  #ansible.builtin.file:
    #path: "{{ dwnlds_dir }}"
    #owner: downloads
    #group: media
    #mode: "0775"
    #recurse: yes
#
#- name: Find all files in the downloads directory
  #ansible.builtin.find:
    #paths: "{{ dwnlds_dir }}"
    #recurse: yes
    #file_type: file
  #register: download_files
#
#- name: Set permissions to 664 for all files in downloads
  #ansible.builtin.file:
    #path: "{{ item.path }}"
    #mode: "0664"
  #loop: "{{ download_files.files }}"
#

#- name: Set permissions for the downloads config directory
  #ansible.builtin.file:
    #path: "{{ app_data_dir }}/deluge"
    #owner: downloads
    #group: media
    #mode: "0775"
    #recurse: yes

#- name: Find all files in the downloads config directory
  #ansible.builtin.find:
    #paths: "{{ app_data_dir }}/deluge"
    #recurse: yes
    #file_type: file
  #register: download_config_files

#- name: Set permissions to 664 for all files in downloads config
  #ansible.builtin.file:
    #path: "{{ item.path }}"
    #mode: "0664"
  #loop: "{{ download_config_files.files }}"

