---
- name: Ensure new Plex container is running
  community.docker.docker_container:
    image_name_mismatch: "recreate"
    pull: "always"
    name: plex
    runtime: nvidia
    image: lscr.io/linuxserver/plex:1.41.2
    security_opts:
      - "label=disable"
    network_mode: "host"
    restart_policy: "unless-stopped"
    env:
      TZ: "{{ timezone }}"
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      NVIDIA_DRIVER_CAPABILITIES: "all"
      NVIDIA_VISIBLE_DEVICES: "GPU-4f06ded6-04b8-a364-9264-027a0333b98f"
      HOST_OS: "Unraid"
      HOST_HOSTNAME: "JohnFlix"
      TCP_PORT_32400: "324001.32.4"
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      HOME: "/home/nobody"
      TERM: "bash"
      LANG: "en_GB.UTF-8"
      VERSION: "docker"
    volumes:
      - "{{ app_data_dir }}/plex:/config"
      - "{{ media_dir }}:/media"
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/binhex/docker-templates/master/binhex/images/plex-icon.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:32400]/web/index.html"
    log_driver: json-file
    log_options:
      max-file: "1"
      max-size: 10m