---
- name: Ensure new Plex container is running
  ansible.builtin.include_tasks: ../../../shared-tasks/docker-app.yml
  vars:
    app_name: plex
    app_image: lscr.io/linuxserver/plex:1.41.2
    app_runtime: nvidia
    app_security_opts:
      - "label=disable"
    app_network_mode: "host"
    app_restart_policy: "unless-stopped"
    app_env:
      TZ: "{{ timezone }}"
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      NVIDIA_DRIVER_CAPABILITIES: "all"
      NVIDIA_VISIBLE_DEVICES: "{{ tesla_p4 }}"
      HOST_OS: "Unraid"
      HOST_HOSTNAME: "JohnFlix"
      TCP_PORT_32400: "324001.32.4"
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      HOME: "/home/nobody"
      TERM: "bash"
      LANG: "en_GB.UTF-8"
      VERSION: "docker"
    app_volumes:
      - "{{ app_data_dir }}/plex:/config"
      - "{{ media_dir }}:/media"
    app_icon_url: "https://raw.githubusercontent.com/binhex/docker-templates/master/binhex/images/plex-icon.png"
    app_webui_url: "http://[IP]:[PORT:32400]/web/index.html"
    app_log_driver: json-file
    app_log_options:
      max-file: "1"
      max-size: 10m
    app_traefik_enable: false
