---
- name: Start ollama container
  ansible.builtin.include_tasks: ../../../shared-tasks/docker-app.yml
  vars:
    app_name: ollama
    app_image: ollama/ollama:0.5.7
    app_runtime: nvidia
    app_env:
      TZ: "{{ timezone }}"
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      NVIDIA_DRIVER_CAPABILITIES: "all"
      NVIDIA_VISIBLE_DEVICES: "{{ tesla_p4 }}"
    app_published_ports: ["11434:11434"]
    app_icon_url: "https://ollama.com/public/ollama.png"
    app_traefik_enable: false
    app_log_driver: json-file
    app_log_options:
      max-file: "1"
      max-size: 10m
    app_restart_policy: always
    app_volumes:
      - "{{ app_data_dir }}/ollama:/root/.ollama"

- name: Start Open WebUI container
  ansible.builtin.include_tasks: ../../../shared-tasks/docker-app.yml
  vars:
    app_name: Open-WebUI
    app_image: ghcr.io/open-webui/open-webui:main
    app_published_ports: ["8383:8080"]
    app_env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      OLLAMA_BASE_URL: "http://{{ local_ip }}:11434"
      WEBUI_AUTH: "False"
    app_ipc_mode: private
    app_icon_url: "https://docs.openwebui.com/images/logo.png"
    app_webui_url: "http://[IP]:8383"
    app_traefik_enable: false
    app_log_driver: json-file
    app_log_options:
      max-file: "1"
      max-size: 10m
    app_network_mode: "host"
    app_restart_policy: always
    app_volumes:
      - "{{ app_data_dir }}/open-webui:/app/backend/data"
    app_etc_hosts:
      host-gateway: ["host.docker.internal"]
