- name: Start 4k-films container
  community.docker.docker_container:
    name: 4k-films
    image: linuxserver/radarr:5.0.3
    entrypoint:
      - /init
    env:
      PATH: /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    networks:
      - name: web
    labels:
      net.unraid.docker.icon: "https://user-images.githubusercontent.com/11823348/114629539-129b9100-9cb9-11eb-94a8-803fabc27d9e.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "https://4k-films.johnflix.uk"
      traefik.enable: "true"
      traefik.http.routers.4k-films.service: "4k-films"
      traefik.http.routers.4k-films.tls.certresolver: "dns-cloudflare"
      traefik.http.routers.4k-films.entrypoints: "websecure"
      traefik.http.services.4k-films.loadbalancer.server.port: "5656"
      traefik.docker.network: "web"
    log_driver: json-file
    log_options:
      max-file: '1'
      max-size: 10m
    restart_policy: always
    volumes:
      - radarr-4k:/config
      - /mnt/user/downloads:/downloads
      - /mnt/user/media/4k-movies:/movies
      - /mnt/user/media/old-4k:/old-4k


- name: Start 4k-tv container
  community.docker.docker_container:
    use_ssh_client: true
    name: 4k-tv
    image: linuxserver/sonarr:3.0.10
    entrypoint:
      - /init
    ipc_mode: private
    labels:
      net.unraid.docker.icon: "https://github.com/themepark-dev/theme.park/blob/master/css/addons/sonarr/sonarr-4k-logo/sonarr-4k.png?raw=true"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "https://4k-tv.johnflix.uk"
      traefik.enable: "true"
      traefik.http.routers.4k-tv.service: "4k-tv"
      traefik.http.routers.4k-tv.tls.certresolver: "dns-cloudflare"
      traefik.http.routers.4k-tv.entrypoints: "websecure"
      traefik.http.services.4k-tv.loadbalancer.server.port: "6767"
      traefik.docker.network: "web"
    log_driver: json-file
    log_options:
      max-file: '1'
      max-size: 10m
    networks:
      - name: web
    restart_policy: always
    volumes:
      - sonarr-4k:/config
      - /mnt/user/downloads:/downloads
      - /mnt/user/media/4k-tv-shows:/tv-shows
      - /mnt/user/media/old-4k:/old-4k
    working_dir: /
