---
- name: Start requests container
  ansible.builtin.include_tasks: ../../../shared-tasks/docker-app.yml
  vars:
    app_name: requests
    app_image: linuxserver/overseerr:1.33.2
    app_published_ports: ["5055:5055/tcp"]
    app_env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ timezone }}"
    app_networks:
      - name: web
    app_icon_url: "https://raw.githubusercontent.com/sct/overseerr/refs/heads/develop/public/android-chrome-192x192_maskable.png"
    app_webui_url: "https://requests.{{ DOMAIN }}"
    app_traefik_enable: true
    app_port: 5055
    app_log_driver: json-file
    app_log_options:
      max-file: "1"
      max-size: 10m
    app_restart_policy: always
    app_volumes:
      - "{{ app_data_dir }}/overseerr:/config"
    app_security_opts:
      - no-new-privileges:true
      - apparmor=docker-default
    app_memory: "1g"
    app_cpus: 1
