---
- name: Start requests container
  community.docker.docker_container:
    image_name_mismatch: "recreate"
    pull: "always"
    name: requests
    image: linuxserver/overseerr:1.33.2
    ports:
      - "5055:5055/tcp"
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ timezone }}"
    networks:
      - name: web
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/sct/overseerr/refs/heads/develop/public/android-chrome-192x192_maskable.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "https://requests.{{ DOMAIN }}"
      #traefik.enable: "true"
      #traefik.http.routers.requests.tls.certresolver: "letsencrypt"
      #traefik.http.routers.requests-router.rule: "Host(`requests.{{ DOMAIN }}`)"
      #traefik.http.routers.requests-router.entrypoints: "https"
      #traefik.http.routers.requests-router.service: requests
      #traefik.http.services.requests.loadbalancer.server.port: "5055"
    log_driver: json-file
    log_options:
      max-file: "1"
      max-size: 10m
    restart_policy: always
    volumes:
      - "{{ app_data_dir }}/overseerr:/config"
    security_opts:
      - no-new-privileges:true
      - apparmor=docker-default
    ##read_only: true
    ##tmpfs:
      ##- "/run:exec"
    memory: "1g"
    cpus: 1