---
- name: Start films container
  ansible.builtin.include_tasks: ../../../shared-tasks/docker-app.yml
  vars:
    app_name: films
    app_image: linuxserver/radarr:5.14.0
    app_env:
      PATH: /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
    app_networks:
      - name: web
    app_published_ports: ["7878:7878"]
    app_icon_url: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/radarr-logo.png"
    app_webui_url: "https://films.{{ DOMAIN }}"
    app_traefik_enable: true
    app_port: 7878
    app_log_driver: json-file
    app_log_options:
      max-file: "1"
      max-size: 10m
    app_restart_policy: always
    app_volumes:
      - "{{ app_data_dir }}/radarr/config:/config"
      - "{{ media_dir }}/Films:/movies"
    app_security_opts:
      - no-new-privileges:true
      - apparmor=docker-default
    app_memory: "1g"
    app_cpus: 1

#- name: Set permissions for sonarr directory
  #ansible.builtin.include_tasks: "../../../shared-tasks/permissions.yml"
  #vars:
    #target_dir: "{{ app_data_dir }}/sonarr"

#- name: Set permissions for tv show directory
  #ansible.builtin.include_tasks: "../../../shared-tasks/permissions.yml"
  #vars:
    #target_dir: "{{ media_dir }}/TV Shows"

- name: Start tv container
  ansible.builtin.include_tasks: ../../../shared-tasks/docker-app.yml
  vars:
    app_name: tv
    app_image: linuxserver/sonarr:4.0.10
    app_published_ports: ["8989:8989"]
    app_env:
      PATH: /lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
    app_ipc_mode: private
    app_icon_url: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sonarr-icon.png"
    app_webui_url: "https://tv.{{ DOMAIN }}"
    app_traefik_enable: true
    app_port: 8989
    app_log_driver: json-file
    app_log_options:
      max-file: "1"
      max-size: 10m
    app_networks:
      - name: web
    app_restart_policy: always
    app_volumes:
    - "{{ app_data_dir }}/sonarr/dev/rtc:/dev/rtc:ro"
    - "{{ app_data_dir }}/sonarr:/config"
    - "{{ dwnlds_dir }}:/downloads"
    - "{{ media_dir }}/TV Shows:/tv"
    app_working_dir: /
    app_security_opts:
      - no-new-privileges:true
      - apparmor=docker-default
    app_memory: "1g"
    app_cpus: 1
