---
- name: Ensure the traefik directory exists
  file:
    path: "{{ app_data_dir }}/traefik-new/"
    state: directory
    mode: '0755'

- name: Ensure the data directory exists
  file:
    path: "{{ app_data_dir }}/traefik-new/data/"
    state: directory
    mode: '0755'

- name: Ensure the config file exists in {{ app_data_dir }}traefik-new/data/configs
  ansible.builtin.stat:
    path: "{{ app_data_dir }}traefik-new/data/traefik.yml"
  register: config_file_stat

- name: Copy the config file to the host if it doesn't exist
  ansible.builtin.copy:
    src: ../files/traefik-config.yml  # Path to the file in your repo (relative to your playbook)
    dest: "{{ app_data_dir }}traefik-new/data/traefik.yml"
    owner: root      # Adjust these as necessary
    group: root
    mode: '0644'
  when: not config_file_stat.stat.exists

- name: Ensure the acme.json file exists in {{ app_data_dir }}traefik-new/data/acme.json
  ansible.builtin.stat:
    path: "{{ app_data_dir }}traefik-new/data/acme.json"
  register: acme_file_stat

- name: Create the acme.json file if it doesn't exist
  ansible.builtin.file:
    path: "{{ app_data_dir }}traefik-new/data/acme.json"
    state: touch
    owner: root
    group: root
    mode: '0600'
  when: not acme_file_stat.stat.exists

- name: Start traefik container
  community.docker.docker_container:
    name: traefik
    image: traefik:v3.0
    container_default_behavior: compatibility
    pull: "always"
    read_only: true
    restart_policy: always
    networks:
      - name: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{ app_data_dir }}/traefik-new/data/traefik.yml:/traefik.yml:ro"
      - "{{ app_data_dir }}/traefik-new/data/configs:/configs:ro"
      - "{{ app_data_dir }}/traefik-new/data/acme.json:/acme.json:rw"
      - "{{ app_data_dir }}/traefik-new/data/logs:/logs:rw"
    env:
      TZ: "{{ timezone }}"
      CF_DNS_API_TOKEN: "{{ CF_KEY }}"
    security_opts:
      - no-new-privileges:true
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik-https.entrypoints: "https"
      traefik.http.routers.traefik-https.rule: "Host('traefik.{{DOMAIN}}')"
      traefik.http.middlewares.traefik-auth.basicauth.users: "{{ username }}"
      traefik.http.routers.traefik-https.middlewares: "traefik-auth"
      traefik.http.routers.traefik-https.service: "api@internal"
      traefik.http.routers.traefik-https.tls.certresolver: "letsencrypt"
      traefik.http.routers.traefik-https.tls.domains[0].main: "{{ DOMAIN }}"
      traefik.http.routers.traefik-https.tls.domains[0].sans: "*.{{DOMAIN}}"
    log_driver: json-file
    log_options:
      max-file: "1"
      max-size: "10m"
    working_dir: "/"