---
- name: Ensure the base Traefik directory exists
  ansible.builtin.file:
    path: "{{ app_data_dir }}/traefik"
    state: directory
    mode: '0755'


- name: Deploy the Traefik configuration using a template
  ansible.builtin.template:
    src: "traefik.yml.j2"
    dest: "{{ app_data_dir }}/traefik/traefik.yml"  # This is a file, not a directory
    owner: root
    group: root
    mode: '0644'
    backup: false

- name: Check if the acme.json file exists
  ansible.builtin.stat:
    path: "{{ app_data_dir }}/traefik/acme.json"
  register: acme_file_stat

- name: Create the acme.json file if it doesn't exist
  ansible.builtin.file:
    path: "{{ app_data_dir }}/traefik/acme.json"  # Ensure this is a file
    state: touch  # This ensures it is a file, not a directory
    owner: root
    group: root
    mode: '0600'
  when: not acme_file_stat.stat.exists

- name: Ensure Traefik container is running
  community.docker.docker_container:
    name: traefik
    image: traefik:v3.1.7
    pull: "always"
    read_only: true
    restart_policy: always
    networks:
      - name: web
    ports:
      - "81:80"
      - "440:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{ app_data_dir }}/traefik/traefik.yml:/traefik.yml:ro"
      - "{{ app_data_dir }}/traefik/configs:/configs:ro"
      - "{{ app_data_dir }}/traefik/acme.json:/acme.json:rw"
      - "{{ app_data_dir }}/traefik/logs:/logs:rw"
    env:
      TZ: "{{ timezone }}"
      CF_DNS_API_TOKEN: "{{ CF_KEY }}"
    security_opts:
      - "no-new-privileges:true"
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik-dashboard.rule: "Host(`proxy.{{ DOMAIN }}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
      traefik.http.routers.traefik-dashboard.entrypoints: "https"
      traefik.http.routers.traefik-dashboard.service: "api@internal"
      traefik.http.routers.traefik-dashboard.tls.certresolver: "letsencrypt"
      traefik.http.middlewares.traefik-auth.basicauth.users: "{{ username }}:{{ PASSWORD_HASH }}"
      traefik.http.middlewares.traefik-dashboard-redirect.headers.customresponseheaders.X-Robots-Tag: "noindex,nofollow"
      traefik.http.routers.traefik-dashboard.middlewares: "traefik-auth, traefik-dashboard-redirect"
      net.unraid.docker.icon: "https://www.clipartmax.com/png/small/63-633339_traefik-docker-swarm-load-balancing.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "https://proxy.{{ DOMAIN }}}"
    log_driver: "json-file"
    log_options:
      max-file: "1"
      max-size: "10m"

- name: Ensure Pi-hole container is running
  community.docker.docker_container:
    name: pihole
    image: pihole/pihole:latest
    pull: "always"
    hostname: "pihole.{{ DOMAIN }}"
    restart_policy: unless-stopped
    networks:
      - name: web
    ports:
      - "82:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/udp"
    volumes:
      - "{{ app_data_dir }}/pihole/etc-pihole:/etc/pihole"
      - "{{ app_data_dir }}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
    labels:
      # Unraid-specific labels
      net.unraid.docker.icon: "https://www.clipartmax.com/png/small/296-2965097_network-wide-ad-blocking-via-your-own-linux-hardware-pihole-logo.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "https://pihole.johnflix.uk"

      # Enable Traefik for Pi-hole container
      traefik.enable: "false"

      # Web Interface (HTTPS) Configuration
      traefik.http.routers.pihole-router.rule: "Host(`pihole.{{ DOMAIN }}`)"
      traefik.http.routers.pihole-router.entrypoints: "https"
      traefik.http.routers.pihole-router.tls.certresolver: "letsencrypt"
      traefik.http.services.pihole.loadbalancer.server.port: "82"  # Set Pi-hole’s internal web port

      # Standard DNS over TCP (port 53)
      traefik.tcp.routers.dns.rule: "HostSNI(`*`)"  # Wildcard for regular DNS
      traefik.tcp.routers.dns.entrypoints: "dns"
      traefik.tcp.routers.dns.service: "pihole-tcp"

      # Define the TCP service for DNS (port 53)
      traefik.tcp.services.pihole-tcp.loadbalancer.server.port: "53"

      # Standard DNS over UDP (port 53)
      traefik.udp.routers.udpdns.entrypoints: "udpdns"
      traefik.udp.routers.udpdns.service: "pihole-udp"

      # Define the UDP service for DNS (port 53)
      traefik.udp.services.pihole-udp.loadbalancer.server.port: "53"

      #traefik.http.routers.traefik-dashboard.middlewares: "traefik-auth, traefik-dashboard-redirect"
    env:
      TZ: "{{ timezone }}"
      WEBPASSWORD: "{{ PASSWORD }}"
      FTLCONF_LOCAL_IPV4: "{{ local_ip }}"
      IPV6: "false"
      VIRTUAL_HOST: "pihole.{{ DOMAIN }}"
    security_opts:
      - "no-new-privileges:true"
    log_driver: "json-file"
    log_options:
      max-file: "1"
      max-size: "10m"


- name: Set up DuckDNS container
  community.docker.docker_container:
    name: duckdns
    image: lscr.io/linuxserver/duckdns:latest
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ timezone }}"
      SUBDOMAINS: "johnflix"
      TOKEN: "{{ DUCK_DNS_TOKEN }}"
      UPDATE_IP: "ipv4"
    volumes:
      - "{{ app_data_dir }}/duckdns/config:/config "
    restart_policy: unless-stopped
    log_driver: "json-file"
    log_options:
      max-file: "1"
      max-size: "10m"
    labels:
      net.unraid.docker.icon: "https://www.duckdns.org/img/ducky_icon.png"
      net.unraid.docker.managed: "dockerman"

- name: Start requests container
  community.docker.docker_container:
    image_name_mismatch: "recreate"
    pull: "always"
    name: requests
    image: linuxserver/overseerr:1.33.2
    ports:
      - "5055:5055/tcp"
    env:
      PUID: "{{ PUID }}"
      PGID: "{{ PGID }}"
      TZ: "{{ timezone }}"
    networks:
      - name: web
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/sct/overseerr/refs/heads/develop/public/android-chrome-192x192_maskable.png"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "https://requests.{{ DOMAIN }}"
      traefik.enable: "true"
      traefik.http.routers.requests.tls.certresolver: "letsencrypt"
      traefik.http.services.requests.loadbalancer.server.port: "5055"
      traefik.http.routers.requests-router.rule: "Host(`request.{{ DOMAIN }}`)"
      traefik.http.routers.requests-router.entrypoints: "https"
    log_driver: json-file
    log_options:
      max-file: "1"
      max-size: 10m
    restart_policy: always
    volumes:
      - "{{ app_data_dir }}/overseerr:/config"
    security_opts:
      - no-new-privileges:true
      - apparmor=docker-default
    ##read_only: true
    ##tmpfs:
      ##- "/run:exec"
    memory: "1g"
    cpus: 1
