---
- name: Check Runner
  hosts: localhost
  become: true
  roles:
    - runner

- name: Ensure Docker and Networks
  hosts: johnflix
  become: false
  roles:
    - common
  vars_files:
    - vars.yml

- name: Deploy Docker Containers
  hosts: johnflix
  become: false
  roles:
    - 4k
    - audiobooks
  vars_files:
    - vars.yml
