---
- name: Check Runner
  hosts: localhost
  become: true
  gather_facts: False
  roles:
    - runner

- name: Set Ansible facts from environment variables
  set_fact:
    EMAIL: "{{ lookup('env', 'EMAIL') }}"
    DUCK_DNS_TOKEN: "{{ lookup('env', 'DUCK_DNS_TOKEN') }}"
    CF_KEY: "{{ lookup('env', 'CF_KEY') }}"
    DOMAIN: "{{ lookup('env', 'DOMAIN') }}"

- name: Ensure Docker and Networks
  hosts: johnflix
  become: false
  roles:
    - common
  vars_files:
    - vars.yml

- name: Deploy Traefik
  hosts: johnflix
  become: false
  pre_tasks:
    - name: Loading environment variables
      tags: always
  roles:
    - web
  vars_files:
    - vars.yml
  vars:
    EMAIL: "{{ EMAIL }}"
    DUCK_DNS_TOKEN: "{{ DUCK_DNS_TOKEN }}"
    CF_KEY: "{{ CF_KEY }}"
    DOMAIN: "{{ DOMAIN }}"

- name: Deploy Docker Containers
  hosts: johnflix
  become: false
  gather_facts: False
  roles:
    - 4k
    - audiobooks
    - books
  vars_files:
    - vars.yml
