---
- name: Check Runner
  hosts: localhost
  become: true
  roles:
    - runner

- name: Ensure Docker and Networks
  hosts: johnflix
  become: false
  roles:
    - common

- name: Deploy Docker Containers
  hosts: johnflix
  become: false
  roles:
    - 4k
