---
- name: Check Runner and Set Variables
  hosts: localhost
  become: true
  gather_facts: false
  roles:
    - runner
  tasks:
    - name: Set Ansible facts from environment variables
      ansible.builtin.set_fact:
        email: "{{ lookup('env', 'EMAIL') }}"
        duck_dns_token: "{{ lookup('env', 'DUCK_DNS_TOKEN') }}"
        cf_key: "{{ lookup('env', 'CF_KEY') }}"
        domain: "{{ lookup('env', 'DOMAIN') }}"
        password_hash: "{{ lookup('env', 'PASSWORD_HASH') }}"
        password: "{{ lookup('env', 'PASSWORD') }}"
        openvpn_user: "{{ lookup('env', 'OPENVPN_USER') }}"
        openvpn_password: "{{ lookup('env', 'OPENVPN_PASSWORD') }}"
        crowdsec_api: "{{ lookup('env', 'CROWDSEC_API') }}"
        deluge_password: "{{ lookup('env', 'DELUGE_PASSWORD') }}"
        sonarr_api_key: "{{ lookup('env', 'SONARR_API_KEY') }}"
        radarr_api_key: "{{ lookup('env', 'RADARR_API_KEY') }}"

- name: Ensure Docker and Networks
  hosts: johnflix
  become: false
  roles:
    - common
  vars_files:
    - vars.yml

- name: Deploy Security Layer
  hosts: johnflix
  become: false
  pre_tasks:
    - name: Loading environment variables
      ansible.builtin.set_fact:
        email: "{{ hostvars['localhost'].email }}"
        duck_dns_token: "{{ hostvars['localhost'].duck_dns_token }}"
        cf_key: "{{ hostvars['localhost'].cf_key }}"
        domain: "{{ hostvars['localhost'].domain }}"
        password_hash: "{{ hostvars['localhost'].password_hash }}"
        password: "{{ hostvars['localhost'].password }}"
        crowdsec_api: "{{ hostvars['localhost'].crowdsec_api }}"
  roles:
    - database
    - security
  vars_files:
    - vars.yml

- name: Deploy Web Layer
  hosts: johnflix
  become: false
  pre_tasks:
    - name: Loading environment variables
      ansible.builtin.set_fact:
        email: "{{ hostvars['localhost'].email }}"
        duck_dns_token: "{{ hostvars['localhost'].duck_dns_token }}"
        cf_key: "{{ hostvars['localhost'].cf_key }}"
        domain: "{{ hostvars['localhost'].domain }}"
        password_hash: "{{ hostvars['localhost'].password_hash }}"
        password: "{{ hostvars['localhost'].password }}"
  roles:
    - web
  vars_files:
    - vars.yml

- name: Deploy Download Layer
  hosts: johnflix
  become: false
  pre_tasks:
    - name: Loading environment variables
      ansible.builtin.set_fact:
        openvpn_user: "{{ hostvars['localhost'].openvpn_user }}"
        openvpn_password: "{{ hostvars['localhost'].openvpn_password }}"
  roles:
    - downloads
  vars_files:
    - vars.yml

- name: Deploy Docker Containers
  hosts: johnflix
  become: false
  gather_facts: false
  roles:
    - arrs_4k
    - arrs
    - plex
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Loading environment variables
      ansible.builtin.set_fact:
        password: "{{ hostvars['localhost'].password }}"
        deluge_password: "{{ hostvars['localhost'].deluge_password }}"
        sonarr_api_key: "{{ hostvars['localhost'].sonarr_api_key }}"
        radarr_api_key: "{{ hostvars['localhost'].radarr_api_key }}"
