---
- name: Check Runner
  hosts: localhost
  become: true
  roles:
    - runner

- name: Ensure Docker and Networks
  hosts: johnflix
  become: false
  roles:
    - common

- name: Deploy Traefik
  hosts: johnflix
  become: false
  pre_tasks:
    - name: Loading environment variables
      tags: always
      set_fact:
        # I write the variables in uppercase so they match the .env file - but you don't have to
        # For booleans I use the strings "true" and "false", and convert them to booleans at this point
        CF_KEY: '{{ lookup("env", "CF_KEY") }}'
        DUCK_DNS_TOKEN: '{{ lookup("env", "DUCK_DNS_TOKEN")}}'
  roles:
    - web

- name: Deploy Docker Containers
  hosts: johnflix
  become: false
  roles:
    - 4k
    - audiobooks
    - books
  vars_files:
    - vars.yml
