---
app_data_dir: /mnt/user/appdata
media_dir:  /mnt/user/media
dwnlds_dir: /mnt/user/appdata/downloads
PUID: "99"
PGID: "100"
media_pgid: "2000"
timezone: Europe/London
username: feves
local_ip: "192.168.1.10"
subnet: "192.168.1.0/24"

